# Generated by Django 6.0.3 on 2026-03-13 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('geeksforgeeks', 'GeeksForGeeks'), ('other', 'Other')], default='other', max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=20)),
                ('status', models.CharField(choices=[('solved', 'Solved'), ('attempted', 'Attempted'), ('revisit', 'Need to Revisit')], default='solved', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('problem_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViaSocketAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viasocket_api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
